image:
  repository: nikore/cfdyndns
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

cronJob:
  enabled: true
  schedule: '30 * * * *'
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  annotations: {}
  labels: {}

env:
  - name: TZ
    value: UTC

secret:
  create: true

  token: ''
  email: ''
  zoneName: ''

resources:
   requests:
     memory: 64Mi
   limits:
     memory: 64Mi